export const products = [
  {
    id: "adizero-adios-pro-4",
    brand: "Adidas",
    series: "Super Range",
    name: "Adizero Adios Pro 4",
    image: "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=400",
    cushion: "High",
    stability: "Low",
    weight: "193",
    flexibility: "Y",
    drop: "8mm",
    price: 300,
    theme: "Speed",
  },
  {
    id: "adizero-prime-x3-strung",
    brand: "Adidas",
    series: "Super Range",
    name: "Adizero Prime X3 Strung",
    image: "https://images.unsplash.com/photo-1606107557195-0e29a4b5b4aa?w=400",
    cushion: "High",
    stability: "Low",
    weight: "182",
    flexibility: "Y",
    drop: "6mm",
    price: 320,
    theme: "Distance",
  },
  {
    id: "ultraboost-5x",
    brand: "Adidas",
    series: "Super Range",
    name: "Ultraboost 5X",
    image: "https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a?w=400",
    cushion: "High",
    stability: "Medium",
    weight: "321",
    flexibility: "Y",
    drop: "10mm",
    price: 250,
    theme: "Comfort",
  },
  {
    id: "adizero-prime-x3-strung-2",
    brand: "Adidas",
    series: "Super Range",
    name: "Adizero Prime X3 Strung",
    image: "https://images.unsplash.com/photo-1549298916-b41d501d3772?w=400",
    cushion: "High",
    stability: "Low",
    weight: "190",
    flexibility: "Y",
    drop: "6mm",
    price: 320,
    theme: "Distance",
  },
  {
    id: "adizero-takumi-sen-11",
    brand: "Adidas",
    series: "Trainers",
    name: "Adizero Takumi Sen 11",
    image: "https://images.unsplash.com/photo-1608231387042-66d1773070a5?w=400",
    cushion: "Medium",
    stability: "Low",
    weight: "185",
    flexibility: "Y",
    drop: "5mm",
    price: 180,
    theme: "Tempo",
  },
  {
    id: "adizero-prime-x3-strung-3",
    brand: "Adidas",
    series: "Super Range",
    name: "Adizero Prime X3 Strung",
    image: "https://images.unsplash.com/photo-1460353581641-37baddab0fa2?w=400",
    cushion: "High",
    stability: "Low",
    weight: "182",
    flexibility: "Y",
    drop: "6mm",
    price: 320,
    theme: "Distance",
  },
];
